import 'package:flatten/app_constant.dart';
import 'package:flatten/controllers/mycontroller/hr_report_controller.dart';
import 'package:flatten/models/attendance.dart';
import 'package:flatten/views/layouts/layout.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:pdf/pdf.dart' as prt;
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'dart:typed_data';

class AttendancePdfFormat extends StatefulWidget {
  const AttendancePdfFormat({super.key});

  @override
  State<AttendancePdfFormat> createState() => _AttendancePdfFormatState();
}

class _AttendancePdfFormatState extends State<AttendancePdfFormat> {
  final HRReportController controller = Get.put(HRReportController());

  Future<Uint8List> _generatePdf(
    final prt.PdfPageFormat format,
    List<ReportEmployeesLoginList> data,
  ) async {
    final pdf = pw.Document();

    // ✅ Use OpenSans (built-in, simple, fully supported)
    final font = await PdfGoogleFonts.openSansRegular();
    final boldFont = await PdfGoogleFonts.openSansBold();

    final today = DateTime.now();
    final dateStr =
        "${today.day.toString().padLeft(2, '0')}-${today.month.toString().padLeft(2, '0')}-${today.year}";

    pdf.addPage(
      pw.MultiPage(
        pageFormat: prt.PdfPageFormat.a4,
        header: (context) => pw.Center(
          child: pw.Text(
            'Daily Attendance Report — $dateStr',
            style: pw.TextStyle(font: boldFont, fontSize: 16),
          ),
        ),
        build: (context) => [
          pw.Table(
            border: pw.TableBorder.all(color: prt.PdfColors.grey600, width: 1),
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(1.5),
              2: const pw.FlexColumnWidth(1.5),
              3: const pw.FlexColumnWidth(1.2),
              4: const pw.FlexColumnWidth(2),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(
                  color: prt.PdfColors.grey300,
                ),
                children: [
                  _headerCell('Name', boldFont),
                  _headerCell('In Time', boldFont),
                  _headerCell('Out Time', boldFont),
                  _headerCell('Work Hrs', boldFont),
                  _headerCell('Remarks', boldFont),
                ],
              ),
              ...data.map((emp) {
                String workHrs = "0 Hrs 0 Min";
                if ((emp.inTime ?? "").isNotEmpty &&
                    (emp.outTime ?? "").isNotEmpty) {
                  Map<String, int> value = calculateWorkHours(
                    emp.inTime!,
                    emp.outTime!,
                  );
                  workHrs =
                      "${value['hours'] ?? 0} Hrs ${value['minutes'] ?? 0} Min";
                }

                return pw.TableRow(
                  decoration: pw.BoxDecoration(
                    color: (emp.remarks?.toLowerCase() == 'absent')
                        ? prt.PdfColors.red100
                        : prt.PdfColors.white,
                  ),
                  children: [
                    _dataCell(emp.employeeName ?? "", font),
                    _dataCell(
                      (emp.inTime ?? "").isEmpty
                          ? "---"
                          : timeStringToStringWithAmPM(
                              railwayTime: emp.inTime!,
                            ),
                      font,
                    ),
                    _dataCell(
                      (emp.outTime ?? "").isEmpty
                          ? "---"
                          : timeStringToStringWithAmPM(
                              railwayTime: emp.outTime!,
                            ),
                      font,
                    ),
                    _dataCell(workHrs, font),
                    _dataCell(emp.remarks ?? "---", font),
                  ],
                );
              }),
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              'Generated by HR System',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: prt.PdfColors.grey600,
                fontStyle: pw.FontStyle.italic,
              ),
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _headerCell(String text, pw.Font font) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text, style: pw.TextStyle(font: font, fontSize: 12)),
    );
  }

  pw.Widget _dataCell(String text, pw.Font font) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text, style: pw.TextStyle(font: font, fontSize: 12)),
    );
  }

  @override
  Widget build(BuildContext context) {
    return GetBuilder<HRReportController>(
      builder: (ctrl) {
        final reportList = ctrl.reportEmployeesLoginList;
        return Layout(
          scrollNeed: false,
          anyWidget: IconButton(
            onPressed: () {
              Navigator.pop(context);
            },
            icon: Icon(Icons.arrow_back),
          ),
          child: reportList.isEmpty
              ? const Center(child: Text('No data available'))
              : PdfPreview(
                  build: (format) =>
                      _generatePdf(prt.PdfPageFormat.a4, reportList),
                  initialPageFormat: prt.PdfPageFormat.a4,
                  // ✅ Default A4 in preview
                  allowPrinting: true,
                  allowSharing: true,
                  canChangeOrientation: true,
                  pdfFileName: 'Attendance_Report.pdf',
                ),
        );
      },
    );
  }
}
